version: '3.8'

services:
  f1_mcp:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - fastf1_cache:/app/fastf1_cache
    environment:
      - FASTF1_CACHE_DIR=/app/fastf1_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/mcp/context"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4

volumes:
  fastf1_cache: 